{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/BOREDGUYS\\SQL2022;portal",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "BOREDGUYS\\SQL2022",
            "database": "portal"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "kind": "SQL",
          "path": "boredguys\\sql2022;portal",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Business",
        "columns": [
          {
            "name": "id",
            "dataType": "string",
            "sourceColumn": "id"
          },
          {
            "name": "code",
            "dataType": "string",
            "sourceColumn": "code"
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name"
          },
          {
            "name": "initialCode",
            "dataType": "string",
            "sourceColumn": "initialCode"
          },
          {
            "name": "isActive",
            "dataType": "boolean",
            "sourceColumn": "isActive"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status"
          },
          {
            "name": "organizationId",
            "dataType": "string",
            "sourceColumn": "organizationId"
          },
          {
            "name": "apiKey",
            "dataType": "string",
            "sourceColumn": "apiKey"
          },
          {
            "name": "tradeName",
            "dataType": "string",
            "sourceColumn": "tradeName"
          },
          {
            "name": "operatedBy",
            "dataType": "string",
            "sourceColumn": "operatedBy"
          },
          {
            "name": "tinNo",
            "dataType": "string",
            "sourceColumn": "tinNo"
          },
          {
            "name": "taxLiable",
            "dataType": "boolean",
            "sourceColumn": "taxLiable"
          },
          {
            "name": "email",
            "dataType": "string",
            "sourceColumn": "email"
          },
          {
            "name": "address",
            "dataType": "string",
            "sourceColumn": "address"
          },
          {
            "name": "address2",
            "dataType": "string",
            "sourceColumn": "address2"
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city"
          },
          {
            "name": "province",
            "dataType": "string",
            "sourceColumn": "province"
          },
          {
            "name": "postalCode",
            "dataType": "string",
            "sourceColumn": "postalCode"
          },
          {
            "name": "contactPerson",
            "dataType": "string",
            "sourceColumn": "contactPerson"
          },
          {
            "name": "position",
            "dataType": "string",
            "sourceColumn": "position"
          },
          {
            "name": "website",
            "dataType": "string",
            "sourceColumn": "website"
          },
          {
            "name": "accountNo",
            "dataType": "string",
            "sourceColumn": "accountNo"
          },
          {
            "name": "telNo",
            "dataType": "string",
            "sourceColumn": "telNo"
          },
          {
            "name": "telNo2",
            "dataType": "string",
            "sourceColumn": "telNo2"
          },
          {
            "name": "mobileNo",
            "dataType": "string",
            "sourceColumn": "mobileNo"
          },
          {
            "name": "mobileNo2",
            "dataType": "string",
            "sourceColumn": "mobileNo2"
          },
          {
            "name": "logo",
            "dataType": "string",
            "sourceColumn": "logo"
          },
          {
            "name": "createdAt",
            "dataType": "dateTime",
            "sourceColumn": "createdAt"
          },
          {
            "name": "updatedAt",
            "dataType": "dateTime",
            "sourceColumn": "updatedAt"
          },
          {
            "name": "taxCode",
            "dataType": "string",
            "sourceColumn": "taxCode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/BOREDGUYS\\SQL2022;portal\",",
                "    dbo_Business = Source{[Schema=\"dbo\",Item=\"Business\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_Business,{{\"ApiKey\", \"ApiKey.1\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayNumberOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfWeek"
          },
          {
            "name": "DayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "DayNameOfWeek"
          },
          {
            "name": "DayNumberOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfMonth"
          },
          {
            "name": "DayNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfYear"
          },
          {
            "name": "WeekNumberOfMonth",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfMonth"
          },
          {
            "name": "WeekNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfYear"
          },
          {
            "name": "MonthNumber",
            "dataType": "int64",
            "sourceColumn": "MonthNumber"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "MonthNumber"
          },
          {
            "name": "QuarterNumber",
            "dataType": "int64",
            "sourceColumn": "QuarterNumber"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MonthYearNumber",
            "dataType": "int64",
            "sourceColumn": "MonthYearNumber"
          },
          {
            "name": "YearMonth",
            "dataType": "string",
            "sourceColumn": "YearMonth"
          },
          {
            "name": "IsWeekend",
            "dataType": "boolean",
            "sourceColumn": "IsWeekend"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          },
          {
            "name": "SpecialDays",
            "dataType": "string",
            "sourceColumn": "SpecialDays"
          },
          {
            "name": "FinancialYear",
            "dataType": "int64",
            "sourceColumn": "FinancialYear"
          },
          {
            "name": "FinancialQuater",
            "dataType": "int64",
            "sourceColumn": "FinancialQuater"
          },
          {
            "name": "FinancialMonth",
            "dataType": "int64",
            "sourceColumn": "FinancialMonth"
          },
          {
            "name": "FirstDateofYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDateofYear"
          },
          {
            "name": "LastDateofYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDateofYear"
          },
          {
            "name": "FirstDateofQuater",
            "dataType": "dateTime",
            "sourceColumn": "FirstDateofQuater"
          },
          {
            "name": "LastDateofQuater",
            "dataType": "dateTime",
            "sourceColumn": "LastDateofQuater"
          },
          {
            "name": "FirstDateofMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDateofMonth"
          },
          {
            "name": "LastDateofMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDateofMonth"
          },
          {
            "name": "FirstDateofWeek",
            "dataType": "dateTime",
            "sourceColumn": "FirstDateofWeek"
          },
          {
            "name": "LastDateofWeek",
            "dataType": "dateTime",
            "sourceColumn": "LastDateofWeek"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/BOREDGUYS\\SQL2022;portal\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "Location",
        "columns": [
          {
            "name": "id",
            "dataType": "string",
            "sourceColumn": "id"
          },
          {
            "name": "code",
            "dataType": "string",
            "sourceColumn": "code"
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name"
          },
          {
            "name": "organizationId",
            "dataType": "string",
            "sourceColumn": "organizationId"
          },
          {
            "name": "businessId",
            "dataType": "string",
            "sourceColumn": "businessId"
          },
          {
            "name": "areaId",
            "dataType": "string",
            "sourceColumn": "areaId"
          },
          {
            "name": "bgLocationCode",
            "dataType": "string",
            "sourceColumn": "bgLocationCode"
          },
          {
            "name": "isActive",
            "dataType": "boolean",
            "sourceColumn": "isActive"
          },
          {
            "name": "isDefault",
            "dataType": "boolean",
            "sourceColumn": "isDefault"
          },
          {
            "name": "color",
            "dataType": "string",
            "sourceColumn": "color"
          },
          {
            "name": "logo",
            "dataType": "string",
            "sourceColumn": "logo"
          },
          {
            "name": "isStore",
            "dataType": "boolean",
            "sourceColumn": "isStore"
          },
          {
            "name": "isExcludeFromInventory",
            "dataType": "boolean",
            "sourceColumn": "isExcludeFromInventory"
          },
          {
            "name": "isExcludeFromPurchasing",
            "dataType": "boolean",
            "sourceColumn": "isExcludeFromPurchasing"
          },
          {
            "name": "isExcludeFromSales",
            "dataType": "boolean",
            "sourceColumn": "isExcludeFromSales"
          },
          {
            "name": "isInTransit",
            "dataType": "boolean",
            "sourceColumn": "isInTransit"
          },
          {
            "name": "taxLiable",
            "dataType": "boolean",
            "sourceColumn": "taxLiable"
          },
          {
            "name": "email",
            "dataType": "string",
            "sourceColumn": "email"
          },
          {
            "name": "tinNo",
            "dataType": "string",
            "sourceColumn": "tinNo"
          },
          {
            "name": "tradeNameCode",
            "dataType": "string",
            "sourceColumn": "tradeNameCode"
          },
          {
            "name": "operatedBy",
            "dataType": "string",
            "sourceColumn": "operatedBy"
          },
          {
            "name": "address",
            "dataType": "string",
            "sourceColumn": "address"
          },
          {
            "name": "address2",
            "dataType": "string",
            "sourceColumn": "address2"
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city"
          },
          {
            "name": "province",
            "dataType": "string",
            "sourceColumn": "province"
          },
          {
            "name": "postalCode",
            "dataType": "string",
            "sourceColumn": "postalCode"
          },
          {
            "name": "contactPerson",
            "dataType": "string",
            "sourceColumn": "contactPerson"
          },
          {
            "name": "position",
            "dataType": "string",
            "sourceColumn": "position"
          },
          {
            "name": "website",
            "dataType": "string",
            "sourceColumn": "website"
          },
          {
            "name": "telNo",
            "dataType": "string",
            "sourceColumn": "telNo"
          },
          {
            "name": "telNo2",
            "dataType": "string",
            "sourceColumn": "telNo2"
          },
          {
            "name": "mobileNo",
            "dataType": "string",
            "sourceColumn": "mobileNo"
          },
          {
            "name": "mobileNo2",
            "dataType": "string",
            "sourceColumn": "mobileNo2"
          },
          {
            "name": "groupCode",
            "dataType": "string",
            "sourceColumn": "groupCode"
          },
          {
            "name": "priceListCode",
            "dataType": "string",
            "sourceColumn": "priceListCode"
          },
          {
            "name": "taxCode",
            "dataType": "string",
            "sourceColumn": "taxCode"
          },
          {
            "name": "discountCode",
            "dataType": "string",
            "sourceColumn": "discountCode"
          },
          {
            "name": "receiptCode",
            "dataType": "string",
            "sourceColumn": "receiptCode"
          },
          {
            "name": "createdAt",
            "dataType": "dateTime",
            "sourceColumn": "createdAt"
          },
          {
            "name": "updatedAt",
            "dataType": "dateTime",
            "sourceColumn": "updatedAt"
          },
          {
            "name": "deletedAt",
            "dataType": "dateTime",
            "sourceColumn": "deletedAt"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/BOREDGUYS\\SQL2022;portal\",",
                "    dbo_Location = Source{[Schema=\"dbo\",Item=\"Location\"]}[Data]",
                "in",
                "    dbo_Location"
              ]
            }
          }
        ]
      },
      {
        "name": "Organization",
        "columns": [
          {
            "name": "id",
            "dataType": "string",
            "sourceColumn": "id"
          },
          {
            "name": "code",
            "dataType": "string",
            "sourceColumn": "code"
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name"
          },
          {
            "name": "userId",
            "dataType": "string",
            "sourceColumn": "userId"
          },
          {
            "name": "isActive",
            "dataType": "boolean",
            "sourceColumn": "isActive"
          },
          {
            "name": "createdAt",
            "dataType": "dateTime",
            "sourceColumn": "createdAt"
          },
          {
            "name": "updatedAt",
            "dataType": "dateTime",
            "sourceColumn": "updatedAt"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/BOREDGUYS\\SQL2022;portal\",",
                "    dbo_Organization = Source{[Schema=\"dbo\",Item=\"Organization\"]}[Data]",
                "in",
                "    dbo_Organization"
              ]
            }
          }
        ]
      },
      {
        "name": "POSInventory",
        "columns": [
          {
            "name": "businessCode",
            "dataType": "string",
            "sourceColumn": "businessCode"
          },
          {
            "name": "locationCode",
            "dataType": "string",
            "sourceColumn": "locationCode"
          },
          {
            "name": "itemCode",
            "dataType": "string",
            "sourceColumn": "itemCode"
          },
          {
            "name": "qty",
            "dataType": "double",
            "sourceColumn": "qty"
          },
          {
            "name": "cost",
            "dataType": "double",
            "sourceColumn": "cost"
          },
          {
            "name": "price",
            "dataType": "double",
            "sourceColumn": "price"
          },
          {
            "name": "reorderPoint",
            "dataType": "double",
            "sourceColumn": "reorderPoint"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/BOREDGUYS\\SQL2022;portal\",",
                "    dbo_POSInventory = Source{[Schema=\"dbo\",Item=\"POSInventory\"]}[Data]",
                "in",
                "    dbo_POSInventory"
              ]
            }
          }
        ]
      },
      {
        "name": "POSSalesReading",
        "columns": [
          {
            "name": "businessCode",
            "dataType": "string",
            "sourceColumn": "businessCode"
          },
          {
            "name": "locationCode",
            "dataType": "string",
            "sourceColumn": "locationCode"
          },
          {
            "name": "tranDate",
            "dataType": "dateTime",
            "sourceColumn": "tranDate"
          },
          {
            "name": "grossSales",
            "dataType": "double",
            "sourceColumn": "grossSales"
          },
          {
            "name": "return",
            "dataType": "double",
            "sourceColumn": "return"
          },
          {
            "name": "void",
            "dataType": "double",
            "sourceColumn": "void"
          },
          {
            "name": "discount",
            "dataType": "double",
            "sourceColumn": "discount"
          },
          {
            "name": "netSales",
            "dataType": "double",
            "sourceColumn": "netSales"
          },
          {
            "name": "vatSales",
            "dataType": "double",
            "sourceColumn": "vatSales"
          },
          {
            "name": "vatAmount",
            "dataType": "double",
            "sourceColumn": "vatAmount"
          },
          {
            "name": "vatExempt",
            "dataType": "double",
            "sourceColumn": "vatExempt"
          },
          {
            "name": "zeroRated",
            "dataType": "double",
            "sourceColumn": "zeroRated"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/BOREDGUYS\\SQL2022;portal\",",
                "    dbo_POSSalesReading = Source{[Schema=\"dbo\",Item=\"POSSalesReading\"]}[Data]",
                "in",
                "    dbo_POSSalesReading"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4b034233-9dd2-4f99-b3f2-cd76a851bbbc",
        "fromTable": "Business",
        "fromColumn": "organizationId",
        "toTable": "Organization",
        "toColumn": "id"
      },
      {
        "name": "e2536b71-7c67-48ac-a5af-a0ae3bd9d75b",
        "fromTable": "Location",
        "fromColumn": "businessId",
        "toTable": "Business",
        "toColumn": "id"
      },
      {
        "name": "f4f919ab-0514-49d1-b721-c821356dbd07",
        "fromTable": "POSSalesReading",
        "fromColumn": "tranDate",
        "toTable": "DimDate",
        "toColumn": "Date"
      },
      {
        "name": "d7fdca4a-7628-49a2-8822-ad852416ef65",
        "fromTable": "POSInventory",
        "fromColumn": "locationCode",
        "toTable": "Location",
        "toColumn": "bgLocationCode"
      },
      {
        "name": "1c69d745-1467-4d13-8f7f-5643f8510c95",
        "fromTable": "POSSalesReading",
        "fromColumn": "locationCode",
        "toTable": "Location",
        "toColumn": "bgLocationCode"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}